kind: pipeline
name: default

steps:
- name: test
  image: python:3.7
  commands:
  - cd ./remotecoach
  - pip install -r requirements.txt
  - ./manage.py test
  environment:
    PGUSER: postgres
    PGDATABASE: remote_coach_dev
    PGPASSWORD: postgres
    PGPORT: 5432
    PGHOST: database

services:
- name: database
  image: postgres
  ports:
  - 5432
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: remote_coach_dev