kind: pipeline
name: default

steps:
- name: test
  image: elixir:latest
  commands:
  - cd ./remote_coach
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
  - mix test
  environment:
    PGUSER: postgres
    PGDATABASE: remote_coach_dev
    PGPASSWORD: postgres
    PGPORT: 5432
    PGHOST: postgresdb



services:
  - name: postgresdb
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: remote_coach_dev