version: '3'

services: 
  django:
    build:
      context: .
    environment:
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: remote_coach_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:12.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata

volumes:
  pgdata: